# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Secure Note' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Secure Note
  pod 'Gloss'
  pod 'couchbase-lite-ios'

  target 'Secure NoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Secure NoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
